### ISSUE TITLE
Inaccurate regex.test info

### ISSUE THREAD

**Issue by Lioness100** [Kikobeats/js-mythbusters#101]
As per https://mythbusters.js.org/#/regexp/global-flag:

> When .test is invoked, the regex keeps internally the state of the search at [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) property.
> 
> This will be cause inconsistent results if you call test method several times:
> 
> ```js
> const regex = new RegExp('o', 'g')
> const greetings = 'Hello, how are you?'
> 
> regex.lastIndex // => 0
> regex.test(greetings) // => true
> regex.lastIndex // => 5
> regex.test(greetings) // => true
> regex.lastIndex // => 9
> regex.test(greetings) // => true
> regex.lastIndex // => 17
> regex.test(greetings) // => false
> regex.lastIndex // => 0
> ```
> As you can see, lastIndex will continue from the last matched result.
> 
> That can be easily avoided just wrapping into a function that will be executed from the beginning every time:
>

```js
const regex = new RegExp('o', 'g')
const greetings = 'Hello, how are you?'
 
const test = (regex, str) => regex.test(str)
 
test(regex, greetings) // => true
```

However, this doesn't actually solve the problem, as the same `Regex` instance (and all of its state) is reused. Instead, did you mean:

```js
const greetings = 'Hello, how are you?'
 
const test = (str) => {
	const regex = new RegExp('o', 'g')
	regex.test(str)
}
 
test(greetings) // => true
```

If so, could I pr this change?

**Comment by Kikobeats** [comment]
Good catch, can you make the PR? 🙂
