### ISSUE TITLE
"Workflow > Boolean condition" seems to be mostly bunk

### ISSUE THREAD

**Issue by Socialery** [Kikobeats/js-mythbusters#17]
For http://mythbusters.js.org/workflow/boolean-conditions.html  
Using https://jsfiddle.net/tj2o7oza/3/  
And tested on both firefox and chrome with multiple runs

 seems to suggest that the "not a myth" is a myth

More indepth discussion in this comment https://news.ycombinator.com/item?id=12393642

**Comment by Kikobeats** [comment]
Thanks for report this. I removed this tip from the index.

I want to review the comments. originally the thing that I wanted to say is about write simple and boolean conditions easy to understand, but yes, currently looks like silly boolean simplification.

I want to write something in this line but definitely I need to think better how to.
