### ISSUE TITLE
This isn't really mythbusting, just spreading myths?

### ISSUE THREAD

**Issue by twirrim** [Kikobeats/js-mythbusters#25]
I like the idea, but two pieces of feedback:

1) The colour scheme is dark and is okay, in general.  However code samples look terrible, particularly comments on them which end up being a dark text on dark background situation.

2) The main point: None of these appear to be actual mythbusting, at least that I've seen so far.  No benchmarks or other repeatable bits of code.  Just "Hey this is better!", which amounts to little more than myths in and of itself.  Mythbusters was all about taking myths, creating an experiment and figuring out if it was true or not. e.g. http://mythbusters.js.org/workflow/math.html at the very least there should be some simple microbenchmarks there.

**Comment by Kikobeats** [comment]
I collect known tips that are true trying to void noise.

Working on progress, but not problem if you think that something is not true. Comments and bibliography are for something. See for example https://github.com/Kikobeats/js-mythbusters/issues/17.

It's easy to say _where is the benchmark_, but see https://github.com/Kikobeats/js-mythbusters/issues/20. Also, Most of the time code need time running to be optimal and not easy to demonstrate in a benchmark.

Could be nice stablish a guidelines for determinate if something is or not a myth.

**Comment by Kikobeats** [comment]
ops, I closed accidentally!

**Comment by tomByrer** [comment]
Did someone say 'ES6 vs ES5' benchmarks'?
https://kpdecker.github.io/six-speed/

**Comment by Kikobeats** [comment]
@tomByrer awesome resource!

I'm going to study and add it as permanent resource :smile: 

In fact I think to set a baseline could be `stable` and `es6` implementation?
