### ISSUE TITLE
Write about optimize-js 'perf-parens'

### ISSUE THREAD

**Issue by amilajack** [Kikobeats/js-mythbusters#32]
https://github.com/nolanlawson/optimize-js

This has become very popular recently. Would be great to clarify why this 'optimization' works.

**Comment by Kikobeats** [comment]
Thanks for the suggestion. Actually I don't know what `perf-parens` means.

Also I think that optimization like this are more related with uglify and co, but yes, could be nice put all in one chapter.

Feel free to start it 😄
