### ISSUE TITLE
Make logo eyes follow cursor

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/js-mythbusters#38]
Please I need that https://codepen.io/loktar00/pen/FmkAd

**Comment by elrumordelaluz** [comment]
[here](http://codepen.io/elrumordelaluz/pen/aWavEG/) it is something could fit.

![ghost](https://cloud.githubusercontent.com/assets/784056/26276929/2a81efc0-3d82-11e7-9ef9-496f2dfd77ad.gif)

**Comment by Kikobeats** [comment]
First of all, I LOVE YOU.

Just the only objetion that I have is if eyes could be rounded. 

Can you make a PR of this? I'm not idea how to insert it.

**Comment by elrumordelaluz** [comment]
> if eyes could be rounded.

Absolutely, have to remove the `.eyelid`.
Here 👇 a _preview_ of the result:

![screen shot 2017-05-20 at 21 57 15](https://cloud.githubusercontent.com/assets/784056/26278949/751ca65e-3da7-11e7-87d0-e630d4a0c180.png)

In case you want to the _blink_ animation, here 👇 the result without remove the `path`:

![blink](https://cloud.githubusercontent.com/assets/784056/26278975/0adb9074-3da8-11e7-87fc-3380d85f50a8.gif)

> Can you make a PR of this? I'm not idea how to insert it.

Sure.
It is necessary to do something to `build` or to run the _App_?
Didn't tried yet, but I'm not seeing anything related in [Readme](https://github.com/Kikobeats/js-mythbusters/blob/master/README.md) or any `script` in [packages.json](https://github.com/Kikobeats/js-mythbusters/blob/master/package.json).

**Comment by Kikobeats** [comment]
Hey,

sorry about that, I migrated how we generate the project and I didn't update the package.json 
correctly 😅.

The content is served from `docs` folder.  We are using [docsify](https://docsify.js.org/) as static content generator. 

If you want to simulate production build in local you can clone the project and do:

```
npm install && npm run dev
```

For replace the current logo (currently is a [png file](https://github.com/Kikobeats/js-mythbusters/blob/master/docs/logo.png)) we need to insert the HTML code for the animated logo version in [all files that references logo.png](https://github.com/Kikobeats/js-mythbusters/search?utf8=%E2%9C%93&q=logo.png&type=)

The CSS necessary need to live at [style.css](https://github.com/Kikobeats/js-mythbusters/blob/master/docs/style.css), or, could be better create logo.css.
