### ISSUE TITLE
Make easy edit from the web

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/js-mythbusters#40]
Because every section of the web is linked with a GitHub file, could be awesomeness link each section with a "Edit File" button for make easy contributions.

Related: https://github.com/QingWei-Li/docsify/issues/162

**Comment by Kikobeats** [comment]
Currently is possible do that (see the issue related)

@elrumordelaluz any design tip about how integrate this in the current UI? 😄

**Comment by elrumordelaluz** [comment]
> any design tip…

@Kikobeats you are thinking about something like a `button` "Edit ✏︎"? one per section or one generic?

**Comment by Kikobeats** [comment]
The button will be placed per each documentation section.

But I'm not sure about:

- Where the button should be stay. top? bottom?
- How the button should be looks. 

I created `edit-button` branch for play with the code. This is how it looks right now:

<img width="1280" alt="screen shot 2017-06-05 at 11 03 54" src="https://cloud.githubusercontent.com/assets/2096101/26777772/b37d56c6-49de-11e7-8e2c-1cfec240ca81.png">

**Comment by elrumordelaluz** [comment]
I'd do something subtle like 👇 
![screen shot 2017-06-05 at 15 04 51](https://cloud.githubusercontent.com/assets/784056/26784949/6c268122-4a00-11e7-95be-c3d759d39d8f.png)

Let me know if you want a PR

**Comment by Kikobeats** [comment]
I added a first iteration, thanks for the tips!

**Comment by elrumordelaluz** [comment]
@Kikobeats nice!
