### ISSUE TITLE
Write about parsing String into Number

### ISSUE THREAD

**Issue by Kikobeats** [Kikobeats/js-mythbusters#45]

**Comment by kurtextrem** [comment]
I'm on mobile so it could be that I'm not seeing everything and I don't want to be rude, but what is this entry "busting"? The comparison table is great to know, but there is a conclusion missing (which is the most useful overall, which has the best performance etc)

**Comment by Kikobeats** [comment]
I'm going to extend the section soon, just was a first try to have something to write, also I added edit file if anybody is interested in contribute

**Comment by Kikobeats** [comment]
@kurtextrem conclusion was written 👍

**Comment by kurtextrem** [comment]
Really well done :)

btw I found eslint converts +"123" to Number("123") automatically. I wanted
to find the reason behind it, and (at least for v8) the latter seemed the
fastest method (would love to test for you, but I'm on mobile and in
hospital so I figured I'd give you a hint)

Am 06.06.2017 21:33 schrieb "Kiko Beats" <notifications@github.com>:

**Comment by Kikobeats** [comment]
@kurtextrem if you find why please make a PR :)
