### ISSUE TITLE
Incorrect array fill example

### ISSUE THREAD

**Issue by hlomzik** [Kikobeats/js-mythbusters#51]
[docs/v8-tips/inline-initialization.md](/Kikobeats/js-mythbusters/blob/master/docs/v8-tips/inline-initialization.md)

```js
var array = []
for (var i = 0; i < 10; i++) array[0] |= i  // Oh no!
```

Should not there be `array[i] |= 0` instead of repeated modifying of one first element? The same for next "correct" example.

**Comment by Kikobeats** [comment]
I think you're right, can you create a PR of this?

**Comment by hlomzik** [comment]
I tried to avoid this part :)
Ok, I'll create soon.
