### ISSUE TITLE
A mention to performance optimization

### ISSUE THREAD

**Issue by ngryman** [Kikobeats/js-mythbusters#58]
Hey me again,

I would suggest a short paragraph to make the user aware of eager optimizations and the fact it is often an enemy.

> Measure it, don't guess it

**Comment by Kikobeats** [comment]
yay!

I understand your point but probably this book is the opposite to meaure it; based on the experience, measure metrics are more related to the context the bench is running, probably with a wrong setup; also major part of the recommendation of this books are more related witht he long time than short time process running.

but yes I need to find a better copy 😄

**Comment by ngryman** [comment]
I totally get your approach and I'm not arguing against it.
I'm just saying that it would be as an opener or something, to explain that if the reader faces a case that is not contained in this guide, he should measure it instead of guessing it :)
