### ISSUE TITLE
Should warn about memory leaks potentials

### ISSUE THREAD

**Issue by GrosSacASac** [Kikobeats/js-mythbusters#61]
https://mythbusters.js.org/#/v8-tips/freeing-memory

using 
> ```
> var foo = { bar: 'hello world' }
> foo.bar = undefined // Efficient way (good)
> ```

can lead to memory leaks because foo keeps the string key "bar" stored potentially forever. Can happen when objects are used as maps.

**Comment by Kikobeats** [comment]
not sure if I understand you, the point here is 

```
foo.bar = undefined // Efficient way (good)
```

instead of 

```
delete foo.bar // Inefficient way (bad)
```

you keep `bar` reference in the object, but this is less aggresive than delete the key for the garbage collector.
