### ISSUE TITLE
Unusual example in the inline-initialization.md

### ISSUE THREAD

**Issue by generalov** [Kikobeats/js-mythbusters#64]
https://github.com/Kikobeats/js-mythbusters/blame/master/docs/v8-tips/inline-initialization.md#L44
```js
var array = []
for (var i = 0; i < 10; i++) array[i] |= 0  // Oh no!
```
```js
var array = []
array[0] = 0
for (var i = 0; i < 10; i++) array[0] |= i 
```
The first one creates an array with 10 elements. The second one creates an array with a single element.

Maybe it's something like this:
```js
var array = new Array(10)
for (var i = 0; i < 10; i++) array[i] = 0
```

**Comment by Kikobeats** [comment]
Thanks!

The original resource was: https://www.html5rocks.com/en/tutorials/speed/v8/

The section tries to explain how v8 hidden class acts in an array initialization from a low level point of view.

I moved the high level part of the content into:
https://github.com/Kikobeats/js-mythbusters/blob/master/docs/array/preallocation.md

Also with a new example 🎉 .

**Comment by generalov** [comment]
Tanks, ´´´const n = 4
const array = Array(0).fill(0) // [ 0, 0, 0, 0 ]
´´´
´Array(n)´?
