### ISSUE TITLE
The variable access tip is outdated

### ISSUE THREAD

**Issue by kurtextrem** [Kikobeats/js-mythbusters#97]
See: https://esbench.com/bench/6147653f6c89f600a570117c.

Not caching the `.length` lookup and using pre-fix `++i` is the fastest way.

**Comment by Kikobeats** [comment]
Can you make a PR?  Just edit the file with your thoughts 🙂

https://github.com/Kikobeats/js-mythbusters/edit/master/docs/workflow/variable-access.md
